---
title: "Old Road Journal Club"
output: html_document
---

Welcome to the website of the Old Road Journal Club. You will be able to find every information related to the ORJC meetings.

## About

The Old Road Campus Journal Club (ORJC) is an **informal get together session for PhD students** to discuss the latest research findings in the field of biomedical research, and share work that we’ve done! The journal club has a focus on **computational biology**, but we also appreciate the diversity of the field and welcome anything related to genetics and genomics. Join us every other Friday at the Wellcome Centre for Human Genetics or Big Data Institute for **cool science** and **pizza & drinks**! 

ORJC is a great place to meet your fellow DPhil students, talk and exchange expertise. Come to one of the meetings and see for yourself! :)

The Journal Club is presently run by Andrew and [Kasia](https://kasia.codes/).

We have an active mailing list to which one can subscribe by sensing an empty email with _SUBSCRIBE_ in subject line to dphil-journal-club@maillist.ox.ac.uk. 

## News

Thanks to generosity of the Wellcome Trust, we will have pizza 🍕 at the lunchtime meetings and thanks to the BDI snacks 🍪 at  the afternoon meetings! 

## Upcoming meetings

In order not to waste food we are asking you to fill this [form](https://forms.gle/u4HyBJBH9EGoaCAV6). It takes only 30 sec, we promise!

<!-- this is the embed code provided by Google -->
  <iframe src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSo1RZXOMEKrjWhNPM_olfk9_rO4xmRtVn2UcBO0vlQJMraPmQr7fAdBPxf6lf56S0Q-CJmwKQ90Ey0/pubhtml?gid=1095847980&single=true" frameborder="0" width="910" height="300" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
<!-- Google embed ends -->

## Past meetings

* 14/02/2020 - Journal Club: [*Genome-wide polygenic scores for common diseases identify individuals with risk equivalent to monogenic mutations*](https://www.nature.com/articles/s41588-018-0183-z) by **Lino Fonseca Ferreira**; [[slides]](https://github.com/Old-Road-Journal-Club/Old-Road-Journal-Club.github.io/blob/master/slides/200214_LinoFerreira.pdf)  
* 31/01/2020 - Seminar: *Non-linear latent variable models for genomics* by [**Kaspar Martens**](https://kasparmartens.rbind.io/), [OxCSML](http://csml.stats.ox.ac.uk/), Department of Statistics, University of Oxford

## Support

Refreshments and drinks are supported by the [Wellcome Trust](https://wellcome.ac.uk/), [Wellcome Centre for Human Genetics](https://www.well.ox.ac.uk/) and the [Big Data Institute](https://www.bdi.ox.ac.uk/). We are very welcomed to our sponsors for bringing the community together over a slice of pizza and great science!
